services:

  bili-jeans-build:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    image: bili-jeans:${IMAGE_TAG:-latest}

  bili-jeans-run:
    image: bili-jeans:${IMAGE_TAG:-latest}
    volumes:
      - ./:/app/bili-jeans/
    command: ["tail", "-f", "/dev/null"]

  bili-jeans-lint:
    image: bili-jeans:${IMAGE_TAG:-latest}
    command: make lint

  bili-jeans-type-hint:
    image: bili-jeans:${IMAGE_TAG:-latest}
    command: make type-hint

  bili-jeans-test:
    image: bili-jeans:${IMAGE_TAG:-latest}
    command: make test
